const typographyStyles = require('./typography');
const typographyPlugin = require('@tailwindcss/typography');

module.exports = {
    content: [
        "./templates/**/*.html",
    ],
    theme: {
        fontSize: {
            '2xs': ['0.75rem', {lineHeight: '1.25rem'}],
            xs: ['0.8125rem', {lineHeight: '1.5rem'}],
            sm: ['0.875rem', {lineHeight: '1.5rem'}],
            base: ['1rem', {lineHeight: '1.75rem'}],
            lg: ['1.125rem', {lineHeight: '1.75rem'}],
            xl: ['1.25rem', {lineHeight: '1.75rem'}],
            '2xl': ['1.5rem', {lineHeight: '2rem'}],
            '3xl': ['1.875rem', {lineHeight: '2.25rem'}],
            '4xl': ['2.25rem', {lineHeight: '2.5rem'}],
            '5xl': ['3rem', {lineHeight: '1'}],
            '6xl': ['3.75rem', {lineHeight: '1'}],
            '7xl': ['4.5rem', {lineHeight: '1'}],
            '8xl': ['6rem', {lineHeight: '1'}],
            '9xl': ['8rem', {lineHeight: '1'}],
        },
        typography: typographyStyles,
        extend: {
            boxShadow: {
                glow: '0 0 4px rgb(0 0 0 / 0.1)',
            },
            maxWidth: {
                lg: '33rem',
                '2xl': '40rem',
                '3xl': '50rem',
                '5xl': '66rem',
            },
            opacity: {
                1: '0.01',
                2.5: '0.025',
                7.5: '0.075',
                15: '0.15',
            },
        },
    },
    safelist: [
        // button styles from .rs helper!
        "rounded-full",
        "bg-zinc-900",
        "py-1",
        "px-3",
        "bg-emerald-400/10",
        "text-emerald-400",
        "ring-1",
        "ring-inset",
        "ring-emerald-400/20",
        "hover:bg-emerald-400/10",
        "hover:text-emerald-300",
        "hover:ring-emerald-300",
        "bg-zinc-800/40",
        "text-zinc-400",
        "ring-zinc-800",
        "hover:bg-zinc-800",
        "hover:text-zinc-300",
        "bg-emerald-500",
        "text-white",
        "hover:bg-emerald-400",
        "ring-white/10",
        "hover:bg-white/5",
        "hover:text-white",
        "hover:text-emerald-500",
        "font-bold",
        // notifications per js added
        "transform",
        "transition",
        "ease-out", 
        "duration-300", 
        "duration-100",
        "opacity-100",
        "opacity-0",
        "translate-y-0",
        "translate-y-2",
        "translate-y-12",
        "-translate-y-12",
        "sm:translate-y-0",
        "sm:translate-x-0",
        "sm:translate-x-2",
        "xui-entering-detail"
    ],
    plugins: [typographyPlugin],
}