name: deploy

on:
  push: 
    branches: 
      - master

jobs:
  restart_service:
    runs-on: ubuntu-22.04

    steps:
      - name: create key file from secret
        env:
          ssh_private_key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
        run: |
          echo "$ssh_private_key" > /tmp/ssh_private_key
          chmod 600 /tmp/ssh_private_key

      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.REMOTE_KNOWN_HOSTS }}

      - name: ssh onto machine and execute the restart script
        env:
          user: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
        run: |
          ssh -i /tmp/ssh_private_key $user@$host /usr/bin/bash /opt/scripts/restart_preiskampf_ui_service.sh

      - name: remove key file
        run: |
          rm /tmp/ssh_private_key